config/routes.rb
Rails.application.routes.draw do
  resources :cantante_cancions
  devise_for :usuarios
  resources :cancions
  resources :cantantes
  root :to => 'inicio#index'
  get 'inicio/index'




end

app/models/cancion.rb
class Cancion < ActiveRecord::Base
  has_many :cantante_cancion
  has_many :cantante, :through => :cantante_cancion
end

app/models/cantante.rb
class Cantante < ActiveRecord::Base
 has_many :cantante_cancion
 has_many :cancion, :through => :cantante_cancion
end

app/models/cantante_cancion.rb
class CantanteCancion < ActiveRecord::Base
  belongs_to :cantante
  belongs_to :cancion
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cancions_controller.rb
class CancionsController < ApplicationController
  before_action :set_cancion, only: [:show, :edit, :update, :destroy]

  # GET /cancions
  # GET /cancions.json
  def index
    @cancions = Cancion.all
  end

  # GET /cancions/1
  # GET /cancions/1.json
  def show
    @cantantes = @cancion.cantante.all

  end


  # GET /cancions/new
  def new
    @cancion = Cancion.new
  end

  # GET /cancions/1/edit
  def edit
  end

  # POST /cancions
  # POST /cancions.json
  def create
    @cancion = Cancion.new(cancion_params)

    respond_to do |format|
      if @cancion.save
        format.html { redirect_to @cancion, notice: 'Cancion was successfully created.' }
        format.json { render :show, status: :created, location: @cancion }
      else
        format.html { render :new }
        format.json { render json: @cancion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cancions/1
  # PATCH/PUT /cancions/1.json
  def update
    respond_to do |format|
      if @cancion.update(cancion_params)
        format.html { redirect_to @cancion, notice: 'Cancion was successfully updated.' }
        format.json { render :show, status: :ok, location: @cancion }
      else
        format.html { render :edit }
        format.json { render json: @cancion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cancions/1
  # DELETE /cancions/1.json
  def destroy
    @cancion.destroy
    respond_to do |format|
      format.html { redirect_to cancions_url, notice: 'Cancion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cancion
      @cancion = Cancion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cancion_params
      params.require(:cancion).permit(:titulo, :letra, :genero, :cantante_id)
    end
end

app/controllers/cantante_cancions_controller.rb
class CantanteCancionsController < ApplicationController
  before_action :set_cantante_cancion, only: [:show, :edit, :update, :destroy]

  # GET /cantante_cancions
  # GET /cantante_cancions.json
  def index
    @cantante_cancions = CantanteCancion.all
  end

  # GET /cantante_cancions/1
  # GET /cantante_cancions/1.json
  def show
  end

  # GET /cantante_cancions/new
  def new
    @cantante_cancion = CantanteCancion.new
  end

  # GET /cantante_cancions/1/edit
  def edit
  end

  # POST /cantante_cancions
  # POST /cantante_cancions.json
  def create
    @cantante_cancion = CantanteCancion.new(cantante_cancion_params)

    respond_to do |format|
      if @cantante_cancion.save
        format.html { redirect_to @cantante_cancion, notice: 'Cantante cancion was successfully created.' }
        format.json { render :show, status: :created, location: @cantante_cancion }
      else
        format.html { render :new }
        format.json { render json: @cantante_cancion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cantante_cancions/1
  # PATCH/PUT /cantante_cancions/1.json
  def update
    respond_to do |format|
      if @cantante_cancion.update(cantante_cancion_params)
        format.html { redirect_to @cantante_cancion, notice: 'Cantante cancion was successfully updated.' }
        format.json { render :show, status: :ok, location: @cantante_cancion }
      else
        format.html { render :edit }
        format.json { render json: @cantante_cancion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cantante_cancions/1
  # DELETE /cantante_cancions/1.json
  def destroy
    @cantante_cancion.destroy
    respond_to do |format|
      format.html { redirect_to cantante_cancions_url, notice: 'Cantante cancion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cantante_cancion
      @cantante_cancion = CantanteCancion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cantante_cancion_params
      params.require(:cantante_cancion).permit(:cantante_id, :cancion_id)
    end
end

app/controllers/cantantes_controller.rb
class CantantesController < ApplicationController
  before_action :set_cantante, only: [:show, :edit, :update, :destroy]

  # GET /cantantes
  # GET /cantantes.json
  def index
    @cantantes = Cantante.all
  end

  # GET /cantantes/1
  # GET /cantantes/1.json
  def show
    @cancions = @cantante.cancion.all
  end

  # GET /cantantes/new
  def new
    @cantante = Cantante.new
  end

  # GET /cantantes/1/edit
  def edit
  end

  # POST /cantantes
  # POST /cantantes.json
  def create
    @cantante = Cantante.new(cantante_params)

    respond_to do |format|
      if @cantante.save
        format.html { redirect_to @cantante, notice: 'Cantante was successfully created.' }
        format.json { render :show, status: :created, location: @cantante }
      else
        format.html { render :new }
        format.json { render json: @cantante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cantantes/1
  # PATCH/PUT /cantantes/1.json
  def update
    respond_to do |format|
      if @cantante.update(cantante_params)
        format.html { redirect_to @cantante, notice: 'Cantante was successfully updated.' }
        format.json { render :show, status: :ok, location: @cantante }
      else
        format.html { render :edit }
        format.json { render json: @cantante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cantantes/1
  # DELETE /cantantes/1.json
  def destroy
    @cantante.destroy
    respond_to do |format|
      format.html { redirect_to cantantes_url, notice: 'Cantante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cantante
      @cantante = Cantante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cantante_params
      params.require(:cantante).permit(:nombre, :genero, :pais)
    end
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cancions_helper.rb
module CancionsHelper
end

app/helpers/cantante_cancions_helper.rb
module CantanteCancionsHelper
end

app/helpers/cantantes_helper.rb
module CantantesHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/cancions/_form.html.erb
<%= form_for(@cancion) do |f| %>
  <% if @cancion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cancion.errors.count, "error") %> prohibited this cancion from being saved:</h2>

      <ul>
      <% @cancion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :letra %><br>
    <%= f.text_area :letra %>
  </div>
  <div class="field">
    <%= f.label :genero %><br>
    <%= f.text_field :genero %>
  </div>
  <div class="field">
    <%= f.label :cantante_id %><br>
    <%= f.select("cantante_id",Cantante.all.collect{|l| [l.nombre, l.id ] }, {include_blank: 'Seleccione Usuario'}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cancions/edit.html.erb
<h1>Editing Cancion</h1>

<%= render 'form' %>

<%= link_to 'Show', @cancion %> |
<%= link_to 'Back', cancions_path %>

app/views/cancions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Canciones</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Letra</th>
      <th>Genero</th>
      <th>Cantante</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cancions.each do |cancion| %>
      <tr>
        <td><%= cancion.titulo %></td>
        <td><%= cancion.letra %></td>
        <td><%= cancion.genero %></td>
        <td><%= cancion.cantante %></td>
        <td><%= link_to 'Show', cancion %></td>
        <td><%= link_to 'Edit', edit_cancion_path(cancion) %></td>
        <td><%= link_to 'Destroy', cancion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cancion', new_cancion_path %>

app/views/cancions/new.html.erb
<h1>New Cancion</h1>

<%= render 'form' %>

<%= link_to 'Back', cancions_path %>

app/views/cancions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @cancion.titulo %>
</p>

<p>
  <strong>Letra:</strong>
  <%= @cancion.letra %>
</p>

<p>
  <strong>Genero:</strong>
  <%= @cancion.genero %>
</p>

<p>
  <strong>Cantante:</strong>
  <%= @cancion.cantante.nombre %>
</p>

<%= link_to 'Edit', edit_cancion_path(@cancion) %> |
<%= link_to 'Back', cancions_path %>

app/views/cantante_cancions/_form.html.erb
<%= form_for(@cantante_cancion) do |f| %>
  <% if @cantante_cancion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cantante_cancion.errors.count, "error") %> prohibited this cantante_cancion from being saved:</h2>

      <ul>
      <% @cantante_cancion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cantante_id %><br>
    <%= f.text_field :cantante_id %>
  </div>
  <div class="field">
    <%= f.label :cancion_id %><br>
    <%= f.text_field :cancion_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cantante_cancions/edit.html.erb
<h1>Editing Cantante Cancion</h1>

<%= render 'form' %>

<%= link_to 'Show', @cantante_cancion %> |
<%= link_to 'Back', cantante_cancions_path %>

app/views/cantante_cancions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cantante Cancions</h1>

<table>
  <thead>
    <tr>
      <th>Cantante</th>
      <th>Cancion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cantante_cancions.each do |cantante_cancion| %>
      <tr>
        <td><%= cantante_cancion.cantante %></td>
        <td><%= cantante_cancion.cancion %></td>
        <td><%= link_to 'Show', cantante_cancion %></td>
        <td><%= link_to 'Edit', edit_cantante_cancion_path(cantante_cancion) %></td>
        <td><%= link_to 'Destroy', cantante_cancion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cantante cancion', new_cantante_cancion_path %>

app/views/cantante_cancions/new.html.erb
<h1>New Cantante Cancion</h1>

<%= render 'form' %>

<%= link_to 'Back', cantante_cancions_path %>

app/views/cantante_cancions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cantante:</strong>
  <%= @cantante_cancion.cantante %>
</p>

<p>
  <strong>Cancion:</strong>
  <%= @cantante_cancion.cancion %>
</p>

<%= link_to 'Edit', edit_cantante_cancion_path(@cantante_cancion) %> |
<%= link_to 'Back', cantante_cancions_path %>

app/views/cantantes/_form.html.erb
<%= form_for(@cantante) do |f| %>
  <% if @cantante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cantante.errors.count, "error") %> prohibited this cantante from being saved:</h2>

      <ul>
      <% @cantante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :genero %><br>
    <%= f.text_field :genero %>
  </div>
  <div class="field">
    <%= f.label :pais %><br>
    <%= f.text_field :pais %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cantantes/edit.html.erb
<h1>Editing Cantante</h1>

<%= render 'form' %>

<%= link_to 'Show', @cantante %> |
<%= link_to 'Back', cantantes_path %>

app/views/cantantes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cantantes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Genero</th>
      <th>Pais</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cantantes.each do |cantante| %>
      <tr>
        <td><%= cantante.nombre %></td>
        <td><%= cantante.genero %></td>
        <td><%= cantante.pais %></td>
        <td><%= link_to 'Show', cantante %></td>
        <td><%= link_to 'Edit', edit_cantante_path(cantante) %></td>
        <td><%= link_to 'Destroy', cantante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cantante', new_cantante_path %>

app/views/cantantes/new.html.erb
<h1>New Cantante</h1>

<%= render 'form' %>

<%= link_to 'Back', cantantes_path %>

app/views/cantantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @cantante.nombre %>
</p>

<p>
  <strong>Genero:</strong>
  <%= @cantante.genero %>
</p>

<p>
  <strong>Pais:</strong>
  <%= @cantante.pais %>
</p>

<%= link_to 'Edit', edit_cantante_path(@cantante) %> |
<%= link_to 'Back', cantantes_path %>

app/views/inicio/index.html.erb
<h1>Blog de Canciones</h1>
<p>Bienvenidos a mi blog</p>

<p>Crea tu usuario</p

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogMusica</title>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
</head>
<body>


  <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>


<%= yield %>

</body>
</html>